name: Model CI
on: 
  push:
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  build-and-test-model:
    name: Build, test, and upload model
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_md
          python -m spacy link en_core_web_md en
      - name: Train model
        run: |
          rasa train
      - name: Run Through Test Stories
        run: |
          rasa test core --stories tests/test_stories.yml --fail-on-prediction-errors
      - name: Cross-validate NLU model
        if: github.event_name == 'pull_request'
        run: |
          rasa test nlu -f 5 --cross-validation
          python format_results.py
      - name: Upload Cross Validation Results
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v2
        with:
          name: cross-validation-result
          path: results.md

  share_cross_validation_result:
    # Separate job to avoid expired GitHub token
    name: Share cross validation results
    runs-on: ubuntu-latest
    needs: [ build-and-test-model ]

    if: github.event_name == 'pull_request'

    steps:
      - name: Download Cross Validation Results
        uses: actions/download-artifact@v2
        continue-on-error: true
        with:
          name: cross-validation-result

      - name: post cross-val results to PR
        uses: amn41/comment-on-pr@comment-file-contents
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: results.md
